/**
 * These are the event names that will be sent from XRHome to the simulator
 */
const SimulatorHMDLinkActionType = {
  READY_FOR_NEW_CONNECTION: 'SIMULATOR/READY_FOR_NEW_CONNECTION',
  CONNECT: 'SIMULATOR/CONNECT',
  DISCONNECT: 'SIMULATOR/DISCONNECT',
  UNLOAD: 'SIMULATOR/UNLOAD',
  RECENTER: 'SIMULATOR/RECENTER',
  CHANGE_CONTROLLER_TYPE: 'SIMULATOR/CHANGE_CONTROLLER_TYPE',
  WEBRTC_OFFER: 'SIMULATOR/WEBRTC_OFFER',
  WEBRTC_ANSWER: 'SIMULATOR/WEBRTC_ANSWER',
  WEBRTC_CONNECTION_CLOSED: 'SIMULATOR/WEBRTC_CONNECTION_CLOSED',
  WEBRTC_CONNECTION_ERROR: 'SIMULATOR/WEBRTC_CONNECTION_ERROR',
  WEBRTC_CONNECTION_SUCCESS: 'SIMULATOR/WEBRTC_CONNECTION_SUCCESS',
}

/**
 * These are event types that will come from the HMD
 */
const RemoteAction = {
  CONTROLLER_POSITION: 'CONTROLLER_POSITION',
  CONTROLLER_ACTION: 'CONTROLLER_ACTION',
}

export {
  SimulatorHMDLinkActionType,
  RemoteAction,
}
